add some probes and update reducers to return { result }.
rangle/augury-labs pull request #8
Opened 2018-08-29 02:57 UTC by santiago-elustondo

1) add some probes (these are by and large not new. only new one is "root zone")
------
2) update reducers to return { result }.

TLDR: changed the abstract `Reducer.deriveShallowState()` method to expect as a return value an object with a `result` property. Other properties in this object may be used by the reducer to maintain private state.

The state of a reducer is often compared to the previous state using strict equality, be it by scanners or by higher-order reducers, to determine whether the lastEvent triggered a "change of state".

Sometimes reducers would like to collect data from a particular event, but not trigger a change of state. A change of state may have reducer-specific semantic implications that are not warranted, and would negatively impact separation of concerns and optimization. Instead, the reducer might would to hold onto this data, and release it during the next state change.

For example: the LastElapsedCD reducer returns a new state every time that the last elapsed change detection cycle changes. It would like to return as part of this state a list of all components change detected during this CD. The lastElapsedCD object would look something like:
```javascript
{
    startEID: ...
    startPerfStamp: ... 
    finishPerfStamp: ...
    componentsChecked: [
       {
           componentType: ...
           startPerfStamp: ...
           finishPerfStamp: ...
       },
       {
           componentType: ...
           startPerfStamp: ...
           finishPerfStamp: ...
       },
    ]
}
```

Now, each component check will arrive during a different event, and we dont want to release a new state every time this happens. We want to wait until we have everything, and release all at once.

This PR updates the reducer API so that the `Reducer.deriveShallowState()` abstract method is expected to return an object, which will be the `ShallowState`. The property `result` in `ShallowState` is what will be used by scanners or higher-order reducers to know if a meaningful change of state has occurred.

2018-08-29 03:18 UTC, santiago-elustondo commented
took a while to do the rebasing, but i got it :)

2018-08-30 19:10 UTC, andrewthauer requested changes
As I mentioned it's probably easier to talk about some of these things in person. I've left some notes to think about. It also looks like you may need to run prettier across the board. Most files don't seem to be following the ruleset defined.

2018-08-30 19:10 UTC, andrewthauer commented on packages/tools/tslint.config.json
> +    "interface-name": false,
I'm not a fan of overriding most of these rules. Most of these are actually good practice to use. In the odd case where something needs to be exempted they should be tslint-disabled inline (ideally with a comment note about why). At the very least in the specific module and not cart blanche across all packages.

2018-08-30 19:10 UTC, andrewthauer commented on packages/core/src/framework/reducers/reducer.ts
> +export interface ShallowState {
I would say types that are exported should be in their own file. Ideally one exported interface, class, etc. within a file.

2018-08-30 19:10 UTC, andrewthauer commented on packages/core/src/framework/reducers/reducer.ts
> +export interface ShallowState {
Can we have a JSDoc style comment to describe what this interface / shape is for. It's definitely not clear by the name alone. Or perhaps consider a more meaningful name?

2018-08-30 19:10 UTC, andrewthauer commented on packages/core/src/framework/reducers/reducer.ts
> +  result?: any,
Can this be typed to `ShallowState<T>` where result is `result?: T`?

2018-08-30 19:10 UTC, andrewthauer commented on packages/core/src/framework/reducers/reducer.ts
> +  auxiliary?: { [key: string]: any }
Naming here seems a bit vague. Auxiliary could mean literal anything. Can we come up with something more clear?

2018-08-30 19:10 UTC, andrewthauer commented on packages/core/src/reducers/current-cycle.ts
> +          startEID: nextEvent.id,
Can we avoid the acronyms and be explicit? For instance calling it `startEventId` would be more appropriate.

2018-08-30 19:10 UTC, andrewthauer commented on packages/core/src/reducers/current-cycle.ts
> +  result: undefined
Might be better to use `null` instead of undefined?

2018-08-30 19:10 UTC, andrewthauer commented on packages/core/src/reducers/current-cycle.ts
> +const INIT_STATE = {
What do you think about being explicit and calling these `INITIAL_STATE` vs `INIT_STATE`? I think it's a bit more clear as init could in theory imply `initialization` instead of `initial`. `DEFAULT_STATE` would also work imo.

2018-08-30 19:10 UTC, andrewthauer commented on packages/core/src/framework/reducers/reducer.ts
>      const nextShallowState = this.deriveShallowState({
As discussed, I think it might be worth considering if there is a way to avoid tracking child state and parent state in order to potentially simplify reconciling. If possible it would be nice give as much responsibility to the child reducers and somehow avoid introducing this concepts of prevPepState, nextDepState. If this the root objective for passing these through can be avoided, or centralized so child reducers do not need to know about the concept this serves it could make it easier to reason about the problem a bit. Anyways, my 2 conceptual cents :)

2018-09-03 19:46 UTC, merged